name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Set up Node and cache dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # 3) Install dependencies
      - run: npm ci

      # 4) Run linters (optional)
      - name: Lint
        run: npm run lint:all

      # 5) Build production build
      - name: Build
        run: npm run build
