name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write # allow the Pages action to publish
      contents: write # allow checkout/push back to repo
      id-token: write # needed if you do OIDC auth (not strictly for Pages)
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # use GITHUB_TOKEN for any git push
          fetch-depth: 0 # full history, so gh-pages branch is visible
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
